//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JF_DonHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JF_DonHang()
        {
            this.JF_SanPham_DonHang = new HashSet<JF_SanPham_DonHang>();
        }
    
        public int id { get; set; }
        public string madonhang { get; set; }
        public string tenkhachhang { get; set; }
        public string email { get; set; }
        public string diachi { get; set; }
        public string sodienthoai { get; set; }
        public Nullable<System.DateTime> ngaygiaohang { get; set; }
        public string thoigiangiaohang { get; set; }
        public string ghichukhachhang { get; set; }
        public Nullable<System.DateTime> ngaydathang { get; set; }
        public Nullable<int> phuongthucthanhtoan { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public Nullable<int> trangthai { get; set; }
        public string motaxuly { get; set; }
        public Nullable<bool> kichhoat { get; set; }
    
        public virtual JF_HinhThucThanhToan JF_HinhThucThanhToan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JF_SanPham_DonHang> JF_SanPham_DonHang { get; set; }
    }
}
