//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JF_LoaiSanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JF_LoaiSanPham()
        {
            this.JF_SanPham = new HashSet<JF_SanPham>();
        }
    
        public int id { get; set; }
        public string ten { get; set; }
        public Nullable<int> thutu { get; set; }
        public string mota { get; set; }
        public Nullable<bool> kichhoat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JF_SanPham> JF_SanPham { get; set; }
    }
}
