//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JF_SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JF_SanPham()
        {
            this.JF_SanPham_DonHang = new HashSet<JF_SanPham_DonHang>();
        }
    
        public int id { get; set; }
        public string ten { get; set; }
        public string hinhdaidien { get; set; }
        public Nullable<int> id_donvitinh { get; set; }
        public Nullable<decimal> giatien { get; set; }
        public Nullable<int> id_loaisanpham { get; set; }
        public Nullable<bool> noibat { get; set; }
        public Nullable<System.DateTime> ngaycapnhat { get; set; }
        public Nullable<bool> hientrangchu { get; set; }
        public string mota { get; set; }
        public Nullable<bool> kichhoat { get; set; }
        public Nullable<decimal> giatruockm { get; set; }
    
        public virtual JF_DonViTinh JF_DonViTinh { get; set; }
        public virtual JF_LoaiSanPham JF_LoaiSanPham { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JF_SanPham_DonHang> JF_SanPham_DonHang { get; set; }
    }
}
