//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JF_SanPham_DonHang
    {
        public int id { get; set; }
        public Nullable<int> id_donhang { get; set; }
        public Nullable<int> id_sanpham { get; set; }
        public Nullable<decimal> soluong { get; set; }
        public Nullable<decimal> giatien { get; set; }
        public Nullable<decimal> thanhtien { get; set; }
        public Nullable<bool> kichhoat { get; set; }
    
        public virtual JF_DonHang JF_DonHang { get; set; }
        public virtual JF_SanPham JF_SanPham { get; set; }
    }
}
