//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JF_ThongTinLienHe
    {
        public int id { get; set; }
        public string ten { get; set; }
        public string diachi { get; set; }
        public string dienthoai { get; set; }
        public string fax { get; set; }
        public string taikhoannganhang { get; set; }
        public string email { get; set; }
        public string taikhoanbuudien { get; set; }
        public string slogan { get; set; }
        public string tencongty { get; set; }
    }
}
