//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core_MVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class jFoodEntities : DbContext
    {
        public jFoodEntities()
            : base("name=jFoodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JF_DonViTinh> JF_DonViTinh { get; set; }
        public virtual DbSet<JF_HinhThucThanhToan> JF_HinhThucThanhToan { get; set; }
        public virtual DbSet<JF_DonHang> JF_DonHang { get; set; }
        public virtual DbSet<JF_Slider> JF_Slider { get; set; }
        public virtual DbSet<JF_SanPham_DonHang> JF_SanPham_DonHang { get; set; }
        public virtual DbSet<JF_LoaiSanPham> JF_LoaiSanPham { get; set; }
        public virtual DbSet<JF_SanPham> JF_SanPham { get; set; }
        public virtual DbSet<JF_ThongTinLienHe> JF_ThongTinLienHe { get; set; }
    
        public virtual ObjectResult<JF_LaySanPhamTheoDonHang_Result> JF_LaySanPhamTheoDonHang(Nullable<int> iddonhang)
        {
            var iddonhangParameter = iddonhang.HasValue ?
                new ObjectParameter("iddonhang", iddonhang) :
                new ObjectParameter("iddonhang", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JF_LaySanPhamTheoDonHang_Result>("JF_LaySanPhamTheoDonHang", iddonhangParameter);
        }
    }
}
